#!/usr/bin/env bash

set -e

print_usage() {
  echo "Compresses a PDF file"
  echo ""
  echo "Usage:"
  echo "  $(basename $0) <input> <output>"
  echo ""
  echo "Example:"
  echo "  $(basename $0) ./some-paper.pdf ./compressed-some-paper.pdf"
}

error_exit() {
  local error_msg="$1"

  echo "Error: $error_msg"
  print_usage
  exit 1
}

command_exists () {
  [ -x "$(command -v "$1")" ]
}

main() {

  if ! command_exists gs; then
    error_exit "Please install ghostscript: brew install ghostscript"
  fi

  if [[ $# -lt 2 ]]; then
    error_exit "Missing input and output PDFs"
  fi

  local input_file="$1"
  local output_file="$2"

  if [[ ! -f "$input_file" ]]; then
    error_exit "Cannot find input file '$input_file'"
  fi

  gs -sDEVICE=pdfwrite -dNOPAUSE -dQUIET \
     -dBATCH -dCompatibilityLevel=1.4 \
     -dPDFSETTINGS=/ebook \
     -sOutputFile="$output_file" "$input_file"
}

main "$@"
